name: Build Pinocchio via Conda
on:
  pull_request:
  push:
    branches:
      - master
      - devel

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        name: [windows-latest-clang-cl]

        include:
          - name: windows-latest-clang-cl
            os: windows-2019
            compiler: clang-cl

    steps:
    - uses: actions/checkout@v2
    - name: Checkout submodules
      run: |
        git submodule update --init
    - uses: goanpeca/setup-miniconda@v1
      with:
        activate-environment: pinocchio
        environment-file: .github/workflows/conda-env.yml
        python-version: 3.7
    - name: Build Pinocchio
      shell: cmd /C CALL {0}
      run: |
        :: unset extra Boost envs
        set Boost_ROOT=
        set BOOST_ROOT_1_69_0=
        set BOOST_ROOT_1_72_0=
        set PATH=%PATH:C:\hostedtoolcache\windows\Boost\1.72.0;=%
    
        :: start building
        call "%programfiles(x86)%\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" amd64
        mkdir build
        pushd build

        set PKG_CONFIG_PATH=%CONDA_PREFIX%\Library\share\pkgconfig:%CONDA_PREFIX%\Library\share\pkgconfig
        cmake ^
          -G "Visual Studio 16 2019" -T "v142" -DCMAKE_GENERATOR_PLATFORM=x64 ^
          -DCMAKE_INSTALL_PREFIX=%CONDA_PREFIX%\Library ^
          -DCMAKE_BUILD_TYPE=Release ^
          -DPYTHON_EXECUTABLE=%CONDA_PREFIX%\python.exe ^
          -DBUILD_WITH_URDF_SUPPORT=ON -DBUILD_PYTHON_INTERFACE=ON ^
          -DCMAKE_CXX_FLAGS="/EHsc /bigobj" ^
          ..
        cmake --build . --config Release --target install
        ctest --output-on-failure
